### ISSUE TITLE
Taxed Award Scheme

### ISSUE THREAD

**Issue by jennifer-hodgson** [hmrc/HMRC-content-style-guide#86]
Use this issue to discuss Taxed Award Scheme in the HMRC content style guide.

**Comment by philjhogg** [comment]
This is covered by the GOV.UK style guide at https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#c > Capitalisation > names of specific, named government schemes known to people outside government. So can probably be removed from the HMRC content style guide.

**Comment by jennifer-hodgson** [comment]
There are a number of entries for different schemes:
* Accrued Income Scheme
* Contracted-out Salary Related Scheme
* Enterprise Investment Scheme
* Non-resident Landlord Scheme
* Rent-a-Room Scheme
* Repayment of Teachers’ Loans scheme
* Save As You Earn schemes (SAYE)

Should we remove all of them, given that this advice already exists, or retain those that have extra guidance about hyphenation, ie:
* Accrued Income Scheme
* Enterprise Investment Scheme

If we do this, will this decision be obvious to users, or will they be confused by not seeing individual entries for these?

**Comment by philjhogg** [comment]
If we covered all these in a single "Schemes" entry and put some context around that these have some specific rules (and that otherwise you follow the GOV.UK style) - would that help?

**Comment by jennifer-hodgson** [comment]
I will draft something. Thanks.

**Comment by stevenaproctor** [comment]
That is great. I would put a 'for example' at the end of the lead-in.

**Comment by jennifer-hodgson** [comment]
I considered this, but they're not, strictly speaking, "examples" (meaning: this is a small sample and there are others too). Rather, it is my understanding that these are intended as a more-or-less exhaustive list of all the schemes that are styled differently. Is that correct?

**Comment by stevenaproctor** [comment]
OK. Maybe...

>Some HMRC schemes are styled in a specific way. These are:

**Comment by jennifer-hodgson** [comment]
I'm being a stickler cos these being examples creates ambiguity :)

I'll add "These are:"
