### ISSUE TITLE
VAT return or VAT Return?

### ISSUE THREAD

**Issue by mickschonhut** [hmrc/HMRC-content-style-guide#97]

**Comment by stevenaproctor** [comment]
@mickschonhut This is in the GOV.UK style guide. It is VAT Return. See https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#vat-return

**Comment by stevenaproctor** [comment]
@mickschonhut If it is OK with you I will close the issue.

**Comment by mickschonhut** [comment]
@stevenaproctor Thanks - that's fine - didn't expect to find it there so didn't look.
